# ui_plotting.R - ggplot/plotly/leaflet-layer builders (variogram, styler,
# descriptive, correlation, PCA, styled points). Pure functions; no
# reactivity. Sourced via ui_helpers.R.


# buffer_multipliers / get_buffer_multiplier live in spatial_helpers.R so
# interpolation workers can resolve them by sourcing that file alone.

# Builds the Map Viewer variogram-quality banner from the per-locality fit
# list. Red = heuristic fallback (fit failed entirely); amber = auto-fit had
# to select a non-converged/singular candidate. Returns NULL when clean.
# `target` limits the banner to the fits a specific map actually used:
# "act" (actual maps), "pre" (predicted maps), or NULL for both (residual
# maps, which derive from both fits).
build_vgm_warning_html <- function(v_fit_list, target = NULL) {
  # "LocA_act" -> "LocA" when the map's target is known, otherwise
  # "LocA (actual)" so mixed banners stay unambiguous.
  display_key <- function(n) {
    base <- sub("_(act|pre)$", "", n)
    if (!is.null(target)) return(base)
    suffix <- if (grepl("_act$", n)) " (actual)" else if (grepl("_pre$", n)) " (predicted)" else ""
    paste0(base, suffix)
  }

  fallback_keys <- character(0)
  flawed_keys <- character(0)
  for (n in names(v_fit_list)) {
    if (!is.null(target) && !grepl(paste0("_", target, "$"), n)) next
    if (isTRUE(attr(v_fit_list[[n]], "is_fallback"))) {
      fallback_keys <- c(fallback_keys, display_key(n))
    } else if (isTRUE(attr(v_fit_list[[n]], "flawed_winner"))) {
      flawed_keys <- c(flawed_keys, display_key(n))
    }
  }
  if (length(fallback_keys) == 0 && length(flawed_keys) == 0) return(NULL)

  red_part <- if (length(fallback_keys) > 0) {
    paste0("<span style='color:red;'>Note: Variogram fit failed for some localities (",
           paste(fallback_keys, collapse = ", "),
           ").<br>A default spherical variogram model was used instead so the map could still be produced. The map is shown, but its spatial structure was not estimated from your data &mdash; interpret interpolations with caution.</span>")
  } else ""
  amber_part <- if (length(flawed_keys) > 0) {
    paste0("<span style='color:#e67700;'>Auto-fit selected a non-converged or singular variogram for: ",
           paste(flawed_keys, collapse = ", "),
           ".<br>No candidate model converged cleanly, so the best-scoring (lowest-error) fit was used to build this map. The map is still valid to explore, but variogram parameters may be imprecise &mdash; interpret interpolations with caution.</span>")
  } else ""
  sep <- if (nzchar(red_part) && nzchar(amber_part)) "<br>" else ""

  paste0("<div class='vgm-fallback-warn' style='font-weight:bold; background:white; padding:5px 25px 5px 5px; border-radius:4px; position:relative;'>",
         "<button onclick='this.parentElement.style.display=\"none\";' style='position:absolute; top:2px; right:2px; background:none; border:none; color:red; font-size:16px; font-weight:bold; cursor:pointer;'>&times;</button>",
         red_part, sep, amber_part,
         "</div>")
}

# TPS GCV diagnostics panel. Curves exist only after the user runs the
# "OPTIMIZE TPS LAMBDA" button (which stores fields::Tps' gcv.grid per
# locality); plain runs — Auto (lambda < 0) or fixed lambda — never store
# one, so every empty state gets an explicit placeholder instead of a
# blank panel.
build_tps_gcv_plot <- function(gcv_list, loc, target = c("act", "pre")) {
  target <- match.arg(target)
  target_label <- if (target == "act") "Actual" else "Predicted"

  placeholder <- function(msg, size = 5) {
    ggplot() +
      annotate("text", x = 4, y = 4, label = msg, size = size, color = "grey40") +
      theme_void()
  }

  keys <- names(gcv_list)
  has_any <- length(keys) > 0 && any(endsWith(keys, paste0("_", target)))
  if (!has_any) {
    return(placeholder(paste0(
      "No GCV curves (", target_label, ") are available for this run.\n",
      "GCV diagnostics are generated by the 'OPTIMIZE TPS LAMBDA' button\n",
      "(TPS Auto-Fit mode in the sidebar); press it to compute them.\n",
      "Runs with a fixed Lambda (e.g. 0 = exact interpolation) have no GCV search to plot."
    ), size = 4.2))
  }

  if (loc == "Total (Combined)") {
    return(placeholder("TPS GCV diagnostics are generated per locality.\nPlease select a specific locality from the dropdown."))
  }

  df <- gcv_list[[paste0(loc, "_", target)]]
  if (is.null(df) || nrow(df) == 0) {
    return(placeholder(paste0(
      "No GCV curve is available for '", loc, "' (", target_label, ").\n",
      "The optimizer skipped or failed for this locality\n",
      "(e.g. fewer than 5 valid points)."
    ), size = 4.5))
  }

  cols <- if (target == "act") c("steelblue", "darkblue") else c("firebrick", "darkred")
  ggplot(df, aes(x = lambda, y = gcv)) +
    geom_line(color = cols[1], linewidth = 1) +
    geom_point(color = cols[2]) +
    scale_x_log10() + theme_minimal() +
    labs(title = paste0("GCV Curve (", target_label, "): ", loc),
         x = "Lambda (Log Scale)", y = "GCV Score")
}

# RF variable-importance dot chart from a randomForest fit. Covariate names
# map to display labels when variable metadata is supplied (NULL keeps raw
# column names); every importance measure the fit carries gets its own panel,
# mirroring randomForest::varImpPlot's content in a labeled ggplot.
build_rf_importance_plot <- function(rf_mod, title, vars_metadata = NULL) {
  imp <- randomForest::importance(rf_mod)
  if (is.null(imp) || nrow(imp) == 0) return(NULL)
  df <- data.frame(Variable = rownames(imp), imp, check.names = FALSE)
  df$Variable <- unname(get_var_labels(df$Variable, vars_metadata))
  long <- tidyr::pivot_longer(df, -Variable, names_to = "Measure", values_to = "Importance")
  long$Variable <- stats::reorder(long$Variable, long$Importance, FUN = max)
  ggplot(long, aes(x = Importance, y = Variable)) +
    geom_segment(aes(x = 0, xend = Importance, yend = Variable), color = "grey70", linewidth = 0.4) +
    geom_point(color = "steelblue", size = 2.5) +
    facet_wrap(~Measure, scales = "free_x") +
    labs(title = title, x = NULL, y = NULL) +
    theme_minimal(base_size = 12) +
    theme(plot.title = element_text(size = 12, face = "bold"))
}

# Rename the ids of a CK cross-variogram (empirical vm + fitted model list)
# to display labels. id_labels is a named character vector keyed by the
# gstat ids; compound cross ids ("a.b") are matched against the exact
# pairwise combinations, so ids containing dots cannot be mis-split.
relabel_ck_variogram <- function(vm, model, id_labels) {
  ids <- names(id_labels)
  if (is.null(ids) || length(ids) == 0) return(list(vm = vm, model = model))
  resolve <- function(lv) {
    if (lv %in% ids) return(id_labels[[lv]])
    for (i in seq_along(ids)) for (j in seq_along(ids)) {
      if (i != j && identical(lv, paste(ids[i], ids[j], sep = "."))) {
        return(paste(id_labels[[i]], id_labels[[j]], sep = " × "))
      }
    }
    lv
  }
  old_lev <- levels(vm$id)
  new_lev <- make.unique(vapply(old_lev, resolve, character(1)), sep = " ")
  levels(vm$id) <- new_lev
  if (!is.null(model) && !is.null(names(model))) {
    names(model) <- vapply(names(model), function(nm) {
      idx <- match(nm, old_lev)
      if (!is.na(idx)) new_lev[idx] else resolve(nm)
    }, character(1))
  }
  list(vm = vm, model = model)
}

# Semivariogram as ggplot, replacing the lattice plot(v_emp, v_fit) look:
# empirical lags as points (hover text carries np / distance / semivariance
# for the plotly expand mode), the fitted model as a line via
# gstat::variogramLine, and an optional manual-tuning overlay (red dashed).
# Identical numbers to the lattice version - presentation only. The `text`
# aesthetic lives on the point layer alone so it cannot fragment the
# grouping of any line layer.
build_variogram_ggplot <- function(v_emp, v_fit = NULL, title = "", subtitle = NULL,
                                   manual_model = NULL) {
  if (is.null(v_emp) || nrow(v_emp) == 0) return(NULL)
  df <- as.data.frame(v_emp)
  max_d <- max(df$dist, na.rm = TRUE)
  # suppressWarnings: `text` is a plotly-only aesthetic; ggplot2 warns
  # "Ignoring unknown aesthetics" at layer construction but keeps the mapping,
  # which is exactly what ggplotly_smart() consumes.
  p <- ggplot(df, aes(x = dist, y = gamma)) +
    suppressWarnings(geom_point(aes(text = paste0("Distance: ", round(dist, 1),
                                                  "\nSemivariance: ", signif(gamma, 4),
                                                  "\nPairs (np): ", np)),
                                color = "steelblue", size = 2, alpha = 0.85))
  if (!is.null(v_fit)) {
    line_df <- tryCatch(gstat::variogramLine(v_fit, maxdist = max_d), error = function(e) NULL)
    if (!is.null(line_df)) {
      p <- p + geom_line(data = line_df, aes(x = dist, y = gamma),
                         inherit.aes = FALSE, color = "#1c3d5a", linewidth = 0.7)
    }
  }
  if (!is.null(manual_model)) {
    m_df <- tryCatch(gstat::variogramLine(manual_model, maxdist = max_d), error = function(e) NULL)
    if (!is.null(m_df)) {
      p <- p + geom_line(data = m_df, aes(x = dist, y = gamma),
                         inherit.aes = FALSE, color = "#e03131", linewidth = 0.8, linetype = "dashed")
    }
  }
  p + expand_limits(y = 0) +
    labs(title = title, subtitle = subtitle, x = "Distance (m)", y = "Semivariance") +
    theme_minimal(base_size = 12) +
    theme(plot.title = element_text(size = 12, face = "bold"),
          plot.subtitle = element_text(size = 9, color = "grey30"))
}

# Directional variogram (anisotropy diagnostic) from calc_directional_variogram:
# one coloured curve per angular cone on shared axes, because the question the
# panel answers ("does the range differ with direction?") is a comparison
# between the curves, which facets would make harder to see.
build_directional_variogram_ggplot <- function(vd, title = "", subtitle = NULL) {
  if (is.null(vd) || nrow(vd) == 0 || !"dir.hor" %in% names(vd)) return(NULL)
  df <- as.data.frame(vd)

  # gstat's alpha is a bearing clockwise from north; spell the axis out so the
  # reader does not have to remember the convention.
  compass <- c("0" = "N-S", "45" = "NE-SW", "90" = "E-W", "135" = "NW-SE")
  ang <- sort(unique(df$dir.hor))
  dir_labels <- vapply(ang, function(a) {
    nm <- compass[[as.character(a)]]
    if (is.null(nm) || is.na(nm)) sprintf("%g°", a) else sprintf("%g° (%s)", a, nm)
  }, character(1))
  df$dir <- factor(df$dir.hor, levels = ang, labels = dir_labels)

  pal <- c("#1f78b4", "#e31a1c", "#33a02c", "#ff7f00", "#6a3d9a", "#b15928")

  # suppressWarnings: `text` is a plotly-only aesthetic (see build_variogram_ggplot).
  ggplot(df, aes(x = dist, y = gamma, colour = dir)) +
    suppressWarnings(geom_point(aes(text = paste0("Direction: ", dir,
                                                  "\nDistance: ", round(dist, 1),
                                                  "\nSemivariance: ", signif(gamma, 4),
                                                  "\nPairs (np): ", np)),
                                size = 1.9, alpha = 0.9)) +
    geom_line(linewidth = 0.6, alpha = 0.9) +
    expand_limits(y = 0) +
    scale_colour_manual(values = rep_len(pal, nlevels(df$dir))) +
    labs(title = title, subtitle = subtitle, x = "Distance (m)",
         y = "Semivariance", colour = "Direction") +
    theme_minimal(base_size = 12) +
    theme(plot.title = element_text(size = 12, face = "bold"),
          plot.subtitle = element_text(size = 9, color = "grey30"),
          legend.position = "bottom")
}

# CK cross-variogram matrix as ggplot: one facet per gstat id (direct and
# cross semivariograms), fitted LMC lines matched to facets by model name.
# Call relabel_ck_variogram first when display labels are wanted; ids absent
# from `model` simply get no line. Same numbers as plot(vm, model = ...).
build_ck_variogram_ggplot <- function(vm, model, title = "") {
  if (is.null(vm) || nrow(vm) == 0) return(NULL)
  df <- as.data.frame(vm)
  lev <- if (is.factor(vm$id)) levels(vm$id) else unique(df$id)
  df$id <- factor(df$id, levels = lev)
  max_d <- max(df$dist, na.rm = TRUE)

  line_df <- NULL
  if (!is.null(model) && !is.null(names(model))) {
    pieces <- lapply(intersect(names(model), lev), function(nm) {
      ld <- tryCatch(gstat::variogramLine(model[[nm]], maxdist = max_d), error = function(e) NULL)
      if (is.null(ld)) return(NULL)
      ld$id <- nm
      ld
    })
    pieces <- Filter(Negate(is.null), pieces)
    if (length(pieces) > 0) {
      line_df <- do.call(rbind, pieces)
      line_df$id <- factor(line_df$id, levels = lev)
    }
  }

  p <- ggplot(df, aes(x = dist, y = gamma)) +
    suppressWarnings(geom_point(aes(text = paste0("Distance: ", round(dist, 1),
                                                  "\nSemivariance: ", signif(gamma, 4),
                                                  "\nPairs (np): ", np)),
                                color = "steelblue", size = 1.8, alpha = 0.85))
  if (!is.null(line_df)) {
    p <- p + geom_line(data = line_df, aes(x = dist, y = gamma),
                       inherit.aes = FALSE, color = "#1c3d5a", linewidth = 0.6)
  }
  p + facet_wrap(~id, scales = "free_y") +
    labs(title = title, x = "Distance (m)", y = "Semivariance") +
    theme_minimal(base_size = 11) +
    theme(plot.title = element_text(size = 12, face = "bold"),
          strip.text = element_text(size = 8.5))
}

# ggplotly conversion that restricts the tooltip to the dedicated `text`
# aesthetic when a layer defines one (avoids the duplicated x/y lines);
# plots without a text aesthetic keep plotly's default tooltip.
ggplotly_smart <- function(p) {
  has_text <- "text" %in% names(p$mapping) ||
    any(vapply(p$layers, function(l) "text" %in% names(l$mapping), logical(1)))
  plotly::ggplotly(p, tooltip = if (has_text) "text" else "all")
}

generate_base_plot <- function(item, input, agro_params = NULL) {
  req(item)
  
  if (item$type == "map" || item$type == "map_combined") {
    
    build_map <- function(obj, label, is_tiled = FALSE, kind = "value") {
      # Point error maps: sample-location errors drawn as markers, mirroring
      # the Map Viewer's Point Residuals panel (never a raster surface).
      if (is.list(obj) && inherits(obj$pts, "sf")) {
        vv <- obj$pts$resid
        abs_max <- suppressWarnings(max(abs(vv), na.rm = TRUE))
        if (is.infinite(abs_max) || is.na(abs_max)) abs_max <- 1
        bp <- ggplot()
        if (!is.null(obj$bound)) {
          bp <- bp + geom_sf(data = sf::st_as_sf(obj$bound), fill = NA,
                             color = "grey35", linewidth = 0.4)
        }
        bp <- bp +
          geom_sf(data = obj$pts, aes(fill = resid),
                  shape = 21, color = "black", size = 3, stroke = 0.3) +
          scale_fill_distiller(palette = resolve_resid_palette(input), direction = 1,
                               limits = c(-abs_max, abs_max), na.value = "grey50",
                               name = NULL) +
          coord_sf()
        return(bp)
      }
      if (inherits(obj, "PackedSpatRaster")) obj <- terra::unwrap(obj)
      pal_name <- input$palette_select %||% "YlOrRd"
      # Registry items carry kind ("value"/"residual"/"uncertainty"); the
      # label grepl is a fallback for items archived before kind existed.
      is_resid <- identical(kind, "residual") ||
        (is.null(kind) && grepl("Residual|Point Error", label))
      is_uncert <- identical(kind, "uncertainty") ||
        (is.null(kind) && grepl("Uncertainty Map", label))
      # Agro/bin class limits are defined on the variable's concentration
      # units: only value surfaces may be classified (mirrors the in-app
      # viewer, which always draws residual/uncertainty layers continuously).
      is_class <- input$color_style %in% c("agro", "bin") && !is_resid && !is_uncert

      if (isTruthy(input$styler_high_contrast)) {
          if (!is_class && !is_resid) pal_name <- "viridis"
      }
      
      leg_name <- NULL
      
      bp <- ggplot() + geom_spatraster(data = obj[[1]])
      
      if (is_resid) {
        vv <- as.vector(terra::values(obj[[1]], na.rm=TRUE))
        abs_max <- max(abs(vv), na.rm = TRUE)
        if(is.infinite(abs_max) || is.na(abs_max)) abs_max <- 1
        resid_pal <- resolve_resid_palette(input)
        bp <- bp + scale_fill_distiller(palette = resid_pal, direction = 1, limits = c(-abs_max, abs_max), na.value = "transparent", name = leg_name) +
          coord_sf()
      } else if (is_class && !is.null(agro_params)) {
        obj_c <- terra::classify(obj[[1]], agro_params$rcl_mat, right = FALSE)
        names(obj_c) <- "category"
        
        labels_to_use <- if(input$color_style == "bin") agro_params$leg_labels else agro_params$labels
        lvls <- data.frame(value = 1:agro_params$n_c, category = labels_to_use)
        levels(obj_c) <- lvls
        
        a_cols <- agro_params$colors
        if (isTruthy(input$styler_high_contrast)) {
            a_cols <- viridis::viridis(agro_params$n_c)
        }
        
        bp <- ggplot() + 
          tidyterra::geom_spatraster(data = obj_c, aes(fill = category)) +
          scale_fill_manual(values = a_cols, 
                            labels = agro_params$leg_labels,
                            na.value = "transparent", name = leg_name, drop = FALSE) +
          coord_sf()
      } else {
        is_viridis <- pal_name %in% c("viridis", "cividis")
        if (input$color_style == "bin" && !is_uncert) {
          if(is_viridis) bp <- bp + scale_fill_viridis_b(option = pal_name, na.value = "transparent", n.breaks = 5, name = leg_name)
          else bp <- bp + scale_fill_fermenter(palette = pal_name, direction = 1, na.value = "transparent", n.breaks = 5, name = leg_name)
        } else {
          if(is_viridis) bp <- bp + scale_fill_viridis_c(option = pal_name, na.value = "transparent", name = leg_name)
          else bp <- bp + scale_fill_distiller(palette = pal_name, direction = 1, na.value = "transparent", name = leg_name)
        }
        bp <- bp + coord_sf()
      }
      bp
    }

    if (item$type == "map") {
      return(build_map(item$obj, item$label, kind = item$kind))
    } else {
      p1 <- build_map(item$obj$act, "Actual", is_tiled = TRUE, kind = item$kind)
      p2 <- build_map(item$obj$pre, "Predicted", is_tiled = TRUE, kind = item$kind)
      return(list(p1 = p1, p2 = p2))
    }
    
  } else {
    return(item$obj)
  }
}

apply_styler_theme <- function(p_obj, input, calibration = 1, item_label = "", item_type = "plot") {
  req(p_obj)
  
  s_title <- (input$styler_title_size %||% 16) * calibration
  s_base  <- (input$styler_base_size %||% 12) * calibration
  s_x     <- (input$styler_x_size %||% 12) * calibration
  s_y     <- (input$styler_y_size %||% 12) * calibration
  s_lab   <- (input$styler_label_size %||% 10) * calibration
  s_leg   <- (input$styler_legend_size %||% 10) * calibration
  
  font_f <- input$styler_font_family %||% "sans"
  
  is_combined <- identical(item_type, "map_combined")
  leg_pos <- input$styler_legend_pos %||% (if (is_combined) "bottom" else "right")
  leg_dir <- input$styler_legend_dir %||% (if (is_combined) "horizontal" else "auto")
  if (leg_dir == "auto") {
    leg_dir <- if (leg_pos %in% c("bottom", "top")) "horizontal" else "vertical"
  }
  leg_text_angle <- as.numeric(input$styler_legend_text_angle %||% (if (is_combined) 90 else 0))

  style_pane <- function(p, label, is_combined_pane = FALSE) {
    f_title <- label
    f_x <- if(isTruthy(input$styler_x_title)) input$styler_x_title else NULL
    f_y <- if(isTruthy(input$styler_y_title)) input$styler_y_title else NULL
    
    key_size <- input$styler_legend_key_size %||% 1.0
    margin_t <- (input$styler_margin_t %||% 10) * calibration
    margin_r <- (input$styler_margin_r %||% 10) * calibration
    margin_b <- (input$styler_margin_b %||% 10) * calibration
    margin_l <- (input$styler_margin_l %||% 15) * calibration
    
    if (is_combined_pane) {
      key_size <- key_size * 0.6
      margin_t <- margin_t * 0.3
      margin_r <- margin_r * 0.3
      margin_b <- margin_b * 0.3
      margin_l <- margin_l * 0.3
    }
    
    legend_theme <- if (is_combined_pane) {
      list(
        legend.key.size = unit(key_size, "cm"),
        legend.key.width = unit(key_size * 2.5, "cm"),
        legend.key.height = unit(key_size * 0.5, "cm")
      )
    } else {
      list(legend.key.size = unit(key_size, "cm"))
    }
    
    p + theme_minimal(base_size = s_base, base_family = font_f) +
      theme(
        plot.title = element_text(size = if(is_combined_pane) s_title * 0.85 else s_title, face = "bold"),
        plot.subtitle = element_text(size = s_title * 0.8),
        axis.title.x = element_text(size = s_x),
        axis.title.y = element_text(size = s_y),
        axis.text = element_text(size = s_lab),
        legend.text = element_text(
          size = if(is_combined_pane) s_leg * 0.85 else s_leg, 
          angle = leg_text_angle,
          hjust = if(leg_text_angle != 0) 0.5 else NULL,
          vjust = if(leg_text_angle != 0) 0.5 else NULL
        ),
        legend.title = element_text(size = if(is_combined_pane) s_leg * 0.85 else s_leg, face = "bold"),
        legend.position = leg_pos,
        legend.direction = leg_dir,
        panel.grid.major = if(isTRUE(input$styler_show_grid)) element_line(color = "grey90") else element_blank(),
        panel.grid.minor = if(isTRUE(input$styler_show_grid)) element_line(color = "grey95") else element_blank(),
        plot.margin = ggplot2::margin(margin_t, margin_r, margin_b, margin_l, unit = "mm"),
        axis.text.x = element_text(
          angle = as.numeric(input$styler_label_orient %||% 0),
          hjust = if(as.numeric(input$styler_label_orient %||% 0) != 0) 1 else 0.5,
          vjust = if(as.numeric(input$styler_label_orient %||% 0) != 0) 1 else 0.5
        )
      ) +
      do.call(theme, legend_theme) +
      labs(title = f_title, x = f_x, y = f_y)
  }

  if (item_type == "map_combined") {
    p1_s <- style_pane(p_obj$p1, "Actual", is_combined_pane = TRUE)
    p2_s <- style_pane(p_obj$p2, "Predicted", is_combined_pane = TRUE)
    
    main_t <- if(isTruthy(input$styler_title)) input$styler_title else item_label
    comb_key_size <- (input$styler_legend_key_size %||% 1.0) * 0.6
    
    return(p1_s + p2_s + plot_layout(ncol = 2, guides = "collect") & 
           theme(legend.position = leg_pos, 
                 legend.direction = leg_dir,
                 legend.key.size = unit(comb_key_size, "cm"),
                 legend.key.width = unit(comb_key_size * 2.5, "cm"),
                 legend.key.height = unit(comb_key_size * 0.5, "cm"),
                 legend.margin = ggplot2::margin(2, 2, 2, 2),
                 legend.box.margin = ggplot2::margin(0, 0, 0, 0),
                 legend.text = element_text(
                   size = s_leg * 0.85,
                   angle = leg_text_angle,
                   hjust = if(leg_text_angle != 0) 0.5 else NULL,
                   vjust = if(leg_text_angle != 0) 0.5 else NULL
                 )) & 
           plot_annotation(title = main_t, theme = theme(plot.title = element_text(size = s_title, face = "bold", family = font_f))))
           
  } else if (inherits(p_obj, "trellis")) {
    f_title <- if(isTruthy(input$styler_title)) input$styler_title else item_label
    f_x <- if(isTruthy(input$styler_x_title)) input$styler_x_title else "Distance"
    f_y <- if(isTruthy(input$styler_y_title)) input$styler_y_title else "Semivariance"
    
    return(update(p_obj, 
           par.settings = list(
             fontsize = list(text = s_base),
             fontfamily = font_f
           ),
           scales = list(x = list(rot = as.numeric(input$styler_label_orient %||% 0))),
           main = list(label = f_title, fontfamily = font_f, cex = s_title/s_base),
           xlab = list(label = f_x, fontfamily = font_f, cex = s_x/s_base),
           ylab = list(label = f_y, fontfamily = font_f, cex = s_y/s_base)))
           
  } else {
    t <- if(isTruthy(input$styler_title)) input$styler_title else item_label
    return(style_pane(p_obj, t))
  }
}

generate_styled_plot <- function(item, input, calibration = 1, agro_params = NULL) {
  base_p <- generate_base_plot(item, input, agro_params)
  apply_styler_theme(base_p, input, calibration, item_label = item$label, item_type = item$type)
}

get_stat_letters <- function(df, var_name, group_col, test_type) {
  df_proc <- df[!is.na(df[[var_name]]) & !is.na(df[[group_col]]), ]
  if (nrow(df_proc) < 3) return(NULL)
  
  df_proc[[group_col]] <- as.factor(as.character(df_proc[[group_col]]))
  n_groups <- length(levels(df_proc[[group_col]]))
  if (n_groups < 2) return(NULL)
  if (nrow(df_proc) <= n_groups) return(NULL)
  
  tryCatch({
    formula_str <- paste0("`", var_name, "` ~ `", group_col, "`")
    aov_res <- aov(as.formula(formula_str), data = df_proc)
    
    if (test_type == "tukey" && n_groups > 2 && requireNamespace("agricolae", quietly = TRUE)) {
      res <- agricolae::HSD.test(aov_res, group_col, console = FALSE)
      df_let <- data.frame(group = rownames(res$groups), letter = as.character(res$groups$groups))
      colnames(df_let)[1] <- group_col
      return(df_let)
    } else if (test_type == "duncan" && n_groups > 2 && requireNamespace("agricolae", quietly = TRUE)) {
      res <- agricolae::duncan.test(aov_res, group_col, console = FALSE)
      df_let <- data.frame(group = rownames(res$groups), letter = as.character(res$groups$groups))
      colnames(df_let)[1] <- group_col
      return(df_let)
    } else if (test_type == "kruskal" && requireNamespace("agricolae", quietly = TRUE)) {
      # BH-adjusted pairwise comparisons, consistent with the correlation
      # table's BH policy.
      res <- agricolae::kruskal(df_proc[[var_name]], df_proc[[group_col]], p.adj = "BH", console = FALSE)
      df_let <- data.frame(group = rownames(res$groups), letter = as.character(res$groups$groups))
      colnames(df_let)[1] <- group_col
      return(df_let)
    } else if (test_type == "anova" || n_groups == 2) {
      s_aov <- summary(aov_res)
      f_val <- s_aov[[1]][["F value"]][1]
      p_val <- s_aov[[1]][["Pr(>F)"]][1]
      df1 <- s_aov[[1]][["Df"]][1]
      df2 <- s_aov[[1]][["Df"]][2]
      
      p_label <- if(is.null(p_val) || is.na(p_val)) "p = N/A" else if(p_val < 0.001) "p < 0.001" else paste0("p = ", signif(p_val, 3))
      f_label <- if(is.null(f_val) || is.na(f_val)) "F = N/A" else paste0("F(", df1, ",", df2, ") = ", round(f_val, 2))
      full_label <- paste0("ANOVA: ", f_label, ", ", p_label)
      
      df_let <- data.frame(group = levels(df_proc[[group_col]]), letter = as.character(full_label))
      colnames(df_let)[1] <- group_col
      return(df_let)
    }
  }, error = function(e) { return(NULL) })
  return(NULL)
}

add_stat_layer <- function(p, df, var_name, group_col, stat_test, stat_letter_pos, facet_var = NULL) {
   if (is.null(stat_test) || length(stat_test) == 0) return(p)
   if (!group_col %in% colnames(df)) return(p)
   
   if (!is.null(facet_var)) {
       vars_to_test <- unique(as.character(df[[facet_var]]))
       all_letters <- data.frame()
       for (v in vars_to_test) {
           sub_df <- df[df[[facet_var]] == v, ]
           l_df <- get_stat_letters(sub_df, "Value", group_col, stat_test[1])
           if (!is.null(l_df)) {
               if (stat_test[1] == "anova") {
                   l_df <- l_df[1, , drop=FALSE]
                   max_y <- max(sub_df$Value, na.rm = TRUE)
                   l_df$y_pos <- max_y + (max_y - min(sub_df$Value, na.rm=TRUE)) * 0.15
               } else if (stat_letter_pos == "top") {
                   max_y <- max(sub_df$Value, na.rm = TRUE)
                   l_df$y_pos <- max_y + (max_y - min(sub_df$Value, na.rm=TRUE)) * 0.1
               } else {
                   form <- as.formula(paste0("Value ~ `", group_col, "`"))
                   agg_df <- aggregate(form, data = sub_df, max, na.rm = TRUE)
                   colnames(agg_df) <- c(group_col, "y_pos")
                   l_df <- merge(l_df, agg_df, by = group_col)
               }
               l_df[[facet_var]] <- v
               all_letters <- rbind(all_letters, l_df)
           }
       }
       if (nrow(all_letters) > 0) {
           if (stat_test[1] == "anova") {
              p <- p + geom_text(data = all_letters, aes(x = -Inf, y = y_pos, label = letter), hjust = -0.1, vjust = 1, size = 3.5, fontface = "italic", inherit.aes = FALSE)
           } else {
              p <- p + geom_text(data = all_letters, aes(x = .data[[group_col]], y = y_pos, label = letter), vjust = -0.5, size = 4, fontface = "bold", inherit.aes = FALSE)
              # vjust = -0.5 draws the glyph above y_pos; the default 5% scale
              # expansion is not always enough headroom, cutting letters in
              # half at the panel top, so widen the upper expansion
              p <- p + scale_y_continuous(expand = expansion(mult = c(0.05, 0.15)))
           }
       }
   } else {
       l_df <- get_stat_letters(df, var_name, group_col, stat_test[1])
       if (!is.null(l_df)) {
           if (stat_test[1] == "anova") {
               l_df <- l_df[1, , drop=FALSE]
               max_y <- max(df[[var_name]], na.rm = TRUE)
               y_pos <- max_y + (max_y - min(df[[var_name]], na.rm=TRUE)) * 0.15
               p <- p + annotate("text", x = -Inf, y = y_pos, label = l_df$letter[1], hjust = -0.1, vjust = 1, size = 4, fontface = "italic")
           } else {
               if (stat_letter_pos == "top") {
                   max_y <- max(df[[var_name]], na.rm = TRUE)
                   y_pos <- max_y + (max_y - min(df[[var_name]], na.rm=TRUE)) * 0.1
                   l_df$y_pos <- y_pos
               } else {
                   agg_df <- aggregate(df[[var_name]] ~ df[[group_col]], FUN=max, na.rm=TRUE)
                   colnames(agg_df) <- c(group_col, "y_pos")
                   l_df <- merge(l_df, agg_df, by = group_col)
               }
               p <- p + geom_text(data = l_df, aes(x = .data[[group_col]], y = y_pos, label = letter), vjust = -0.5, size = 4, fontface = "bold", inherit.aes = FALSE)
               # Same headroom fix as the faceted branch: keep the letters
               # from being clipped at the panel top
               p <- p + scale_y_continuous(expand = expansion(mult = c(0.05, 0.15)))
           }
       }
   }
   return(p)
}



# Categorical group axes (boxplot/violin/sina): when many groups or long
# interaction labels ("A | B | C") would crowd the x axis, drop the axis
# text entirely, since group identity is already colour-coded in the legend
hide_x_labels_if_crowded <- function(p, df, group_col) {
  if (is.null(group_col) || !group_col %in% colnames(df)) return(p)
  lv <- unique(as.character(df[[group_col]]))
  lv <- lv[!is.na(lv)]
  if (length(lv) >= 6 || (length(lv) > 1 && max(nchar(lv)) > 12)) {
    p <- p + theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(),
                   axis.title.x = element_blank())
  }
  return(p)
}

# Variable-name x axes (parallel coordinates): the names are NOT in the
# legend, so rotate rather than hide when crowded
rotate_x_labels_if_crowded <- function(p, df, group_col) {
  if (is.null(group_col) || !group_col %in% colnames(df)) return(p)
  lv <- unique(as.character(df[[group_col]]))
  lv <- lv[!is.na(lv)]
  if (length(lv) >= 6 || (length(lv) > 1 && max(nchar(lv)) > 12)) {
    p <- p + theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))
  }
  return(p)
}

generate_core_plot <- function(df, var_name, y_var = NULL, group_col = NULL, plot_type = "histogram", scatter_fit = "none", stat_test = NULL, stat_letter_pos = "above") {


  
  if (is.null(group_col) || !group_col %in% colnames(df)) {
    df$group_id <- factor("All")
    group_col <- "group_id"
  }
  
  if (!"index_seq" %in% colnames(df)) df$index_seq <- seq_len(nrow(df))
  
  p <- ggplot() + theme_minimal()
  
  if (plot_type %in% c("boxplot", "violin") && !is.null(y_var) && y_var != "") {

    df_long <- pivot_longer(df, cols = c(all_of(var_name), all_of(y_var)), names_to = "Variable", values_to = "Value")
    
    if (plot_type == "boxplot") {
      p <- ggplot(df_long, aes(x = .data[[group_col]], y = Value, fill = .data[[group_col]])) + geom_boxplot()
    } else {
      p <- ggplot(df_long, aes(x = .data[[group_col]], y = Value, fill = .data[[group_col]])) + geom_violin(alpha = 0.7)
    }
    p <- p + facet_wrap(~Variable, scales = "free_y") + theme_minimal() +
         labs(title = paste(tools::toTitleCase(plot_type), "Comparison"), x = "Group", y = "Value", fill = "Group")
    p <- add_stat_layer(p, df_long, "Value", group_col, stat_test, stat_letter_pos, facet_var = "Variable")
    p <- hide_x_labels_if_crowded(p, df_long, group_col)
  } else {
    p <- ggplot(df) + theme_minimal()
    
    if (plot_type == "histogram") {
      p <- p + geom_histogram(aes(x = .data[[var_name]], fill = .data[[group_col]]), alpha = 0.7, position = "identity", bins = 30)
    } else if (plot_type == "density") {
      p <- p + geom_density(aes(x = .data[[var_name]], fill = .data[[group_col]], color = .data[[group_col]]), alpha = 0.5)
    } else if (plot_type == "boxplot") {
      p <- p + geom_boxplot(aes(x = .data[[group_col]], y = .data[[var_name]], fill = .data[[group_col]]))
    } else if (plot_type == "violin") {
      p <- p + geom_violin(aes(x = .data[[group_col]], y = .data[[var_name]], fill = .data[[group_col]]), alpha = 0.7)
    } else if (plot_type == "scatter") {
      if (!is.null(y_var) && y_var %in% colnames(df) && y_var != "") {
        p <- p + geom_point(aes(x = .data[[var_name]], y = .data[[y_var]], color = .data[[group_col]]), alpha = 0.8)
      } else {
        df$index_seq <- seq_len(nrow(df))
        p <- p + geom_point(aes(x = .data[["index_seq"]], y = .data[[var_name]], color = .data[[group_col]]), alpha = 0.8)
      }
      
      if (!is.null(scatter_fit) && scatter_fit != "none") {
         fit_methods <- list(
           linear = list(method = "lm", se = FALSE),
           loess = list(method = "loess", se = FALSE),
           polynomial = list(method = "lm", formula = y ~ poly(x, 2), se = FALSE),
           gam = list(method = "gam", formula = y ~ s(x, bs = "cs"), se = FALSE)
         )
         fit_params <- fit_methods[[scatter_fit]]
         if (!is.null(fit_params)) {
           x_col <- if (!is.null(y_var) && y_var != "") var_name else "index_seq"
           y_col <- if (!is.null(y_var) && y_var != "") y_var else var_name
           fit_params$mapping <- aes(x = .data[[x_col]], y = .data[[y_col]], color = .data[[group_col]])
           p <- p + do.call(geom_smooth, fit_params)
         }
      }
      
    } else if (plot_type == "ecdf") {
      p <- p + stat_ecdf(aes(x = .data[[var_name]], color = .data[[group_col]]), geom = "step", linewidth = 1)
    }
    
    if (plot_type %in% c("boxplot", "violin")) {
      p <- add_stat_layer(p, df, var_name, group_col, stat_test, stat_letter_pos)
      p <- hide_x_labels_if_crowded(p, df, group_col)
    }
    
    p <- p + labs(title = paste(tools::toTitleCase(plot_type), "of", var_name),
                  fill = "Group", color = "Group")
  }
  
  return(p)
}

generate_ghosted_plot <- function(df_global, df_local, var_name, y_var = NULL, group_col = NULL, plot_type = "histogram") {

  
  if (is.null(group_col) || !group_col %in% colnames(df_local)) {
    df_local$group_id <- factor("All")
    df_global$group_id <- factor("All")
    group_col <- "group_id"
  }
  
  p <- ggplot() + theme_minimal()
  
  if (plot_type == "histogram") {
    p <- p + geom_histogram(data = df_global, aes(x = .data[[var_name]]), fill = "lightgray", alpha = 0.5, bins = 30) +
             geom_histogram(data = df_local, aes(x = .data[[var_name]], fill = .data[[group_col]]), alpha = 0.7, position = "identity", bins = 30)
  } else if (plot_type == "density") {
    p <- p + geom_density(data = df_global, aes(x = .data[[var_name]]), fill = "lightgray", color = "gray", alpha = 0.3) +
             geom_density(data = df_local, aes(x = .data[[var_name]], fill = .data[[group_col]], color = .data[[group_col]]), alpha = 0.5)
  } else if (plot_type == "boxplot") {
    p <- p + geom_boxplot(data = df_global, aes(x = "Global", y = .data[[var_name]]), fill = "lightgray", color = "gray") +
             geom_boxplot(data = df_local, aes(x = .data[[group_col]], y = .data[[var_name]], fill = .data[[group_col]]))
  } else if (plot_type == "violin") {
    p <- p + geom_violin(data = df_global, aes(x = "Global", y = .data[[var_name]]), fill = "lightgray", color = "gray") +
             geom_violin(data = df_local, aes(x = .data[[group_col]], y = .data[[var_name]], fill = .data[[group_col]]), alpha = 0.7)
  } else if (plot_type == "scatter") {
    if (!is.null(y_var) && y_var %in% colnames(df_local)) {
      p <- p + geom_point(data = df_global, aes(x = .data[[var_name]], y = .data[[y_var]]), color = "lightgray", alpha = 0.3) +
               geom_point(data = df_local, aes(x = .data[[var_name]], y = .data[[y_var]], color = .data[[group_col]]), alpha = 0.8)
    } else {
      df_global$index_seq <- seq_len(nrow(df_global))
      df_local$index_seq <- seq_len(nrow(df_local))
      p <- p + geom_point(data = df_global, aes(x = .data[["index_seq"]], y = .data[[var_name]]), color = "lightgray", alpha = 0.3) +
               geom_point(data = df_local, aes(x = .data[["index_seq"]], y = .data[[var_name]], color = .data[[group_col]]), alpha = 0.8)
    }
  } else if (plot_type == "ecdf") {
    p <- p + stat_ecdf(data = df_global, aes(x = .data[[var_name]]), geom = "step", color = "lightgray", linewidth = 1) +
             stat_ecdf(data = df_local, aes(x = .data[[var_name]], color = .data[[group_col]]), geom = "step", linewidth = 1)
  }
  
  p <- p + labs(title = paste("Ghosted", tools::toTitleCase(plot_type), "of", var_name),
                x = var_name, fill = "Group", color = "Group")

  if (plot_type %in% c("boxplot", "violin")) {
    p <- hide_x_labels_if_crowded(p, df_local, group_col)
  }

  return(p)
}

generate_advanced_plot <- function(df, vars, group_col = NULL, plot_type = "qq", xyz_fit = "linear", stat_test = NULL, stat_letter_pos = "above") {


  
  if (is.null(group_col) || !group_col %in% colnames(df)) {
    df$group_id <- factor("All")
    group_col <- "group_id"
  }
  
  p <- ggplot() + theme_minimal()
  v1 <- if(length(vars) > 0 && isTruthy(vars[1]) && vars[1] != "") vars[1] else NULL
  v2 <- if(length(vars) > 1 && isTruthy(vars[2]) && vars[2] != "") vars[2] else NULL
  v3 <- if(length(vars) > 2 && isTruthy(vars[3]) && vars[3] != "") vars[3] else NULL
  
  if (plot_type == "qq") {
    p <- ggplot(df, aes(sample = .data[[v1]], color = .data[[group_col]])) + 
         stat_qq() + stat_qq_line() + labs(x="Theoretical", y="Sample", title="QQ Plot")
  } else if (plot_type == "sinaplot") {
    if (!is.null(v2) && v2 != "") {
       df_long <- tidyr::pivot_longer(df, cols = c(all_of(v1), all_of(v2)), names_to = "Variable", values_to = "Value")
       p <- ggplot(df_long, aes(x = .data[[group_col]], y = Value, fill = .data[[group_col]])) + 
            geom_violin(alpha=0.5, color=NA) + 
            geom_jitter(aes(color = .data[[group_col]]), width = 0.2, alpha=0.7) +
            facet_wrap(~Variable, scales="free_y") +
            labs(title="Sina-style Plot Comparison")
       
       p <- add_stat_layer(p, df_long, "Value", group_col, stat_test, stat_letter_pos, facet_var = "Variable")
       p <- hide_x_labels_if_crowded(p, df_long, group_col)
    } else {
       p <- ggplot(df, aes(x = .data[[group_col]], y = .data[[v1]], fill = .data[[group_col]])) +
            geom_violin(alpha=0.5, color=NA) +
            geom_jitter(aes(color = .data[[group_col]]), width = 0.2, alpha=0.7) +
            labs(title="Sina-style Plot")

       p <- add_stat_layer(p, df, v1, group_col, stat_test, stat_letter_pos)
       p <- hide_x_labels_if_crowded(p, df, group_col)
    }
  } else if (plot_type %in% c("ridge", "joyplot")) {
    p <- ggplot(df, aes(x = .data[[v1]], fill = .data[[group_col]])) + 
         geom_density(alpha = 0.6) + 
         facet_grid(as.formula(paste(group_col, "~ ."))) +
         labs(title="Ridge/Joyplot Proxy")
  } else if (plot_type == "density_heatmap") {
    if (!is.null(v2)) {
      p <- ggplot(df, aes(x = .data[[v1]], y = .data[[v2]])) + 
           geom_density_2d_filled(alpha = 0.9) +
           labs(title="2D Density Heatmap")
    } else {
      p <- ggplot() + annotate("text", x=0, y=0, label="Density Heatmap requires two numeric variables")
    }
  } else if (plot_type == "parallel") {
    if (length(vars) > 1) {
      df_sub <- df[, c(vars, group_col), drop=FALSE]
      df_sub$id <- seq_len(nrow(df_sub))
      long_df <- data.frame(id = integer(), variable = character(), value = numeric(), group = character())
      for(v in vars) {
        if(is.numeric(df_sub[[v]])) {
          rng <- range(df_sub[[v]], na.rm=TRUE)
          norm_val <- if(diff(rng) > 0) (df_sub[[v]] - rng[1]) / diff(rng) else 0
          long_df <- rbind(long_df, data.frame(id=df_sub$id, variable=v, value=norm_val, group=as.character(df_sub[[group_col]])))
        }
      }
      p <- ggplot(long_df, aes(x=variable, y=value, group=id, color=group)) +
           geom_line(alpha=0.4) + labs(title="Parallel Coordinates")
      p <- rotate_x_labels_if_crowded(p, long_df, "variable")
    } else {
      p <- ggplot() + annotate("text", x=0, y=0, label="Parallel coords requires >=2 vars")
    }
  } else if (plot_type == "radar") {
    if (length(vars) > 2) {
      agg <- aggregate(df[, vars, drop=FALSE], by=list(group=df[[group_col]]), FUN=mean, na.rm=TRUE)
      long_df <- data.frame(group = character(), variable = character(), value = numeric())
      for(v in vars) {
        rng <- range(df[[v]], na.rm=TRUE)
        norm_val <- if(diff(rng) > 0) (agg[[v]] - rng[1])/diff(rng) else 0
        long_df <- rbind(long_df, data.frame(group=agg$group, variable=v, value=norm_val))
      }
      p <- ggplot(long_df, aes(x=variable, y=value, group=group, color=group, fill=group)) +
           geom_polygon(alpha=0.2) + geom_point() + coord_polar() + 
           theme_minimal() + labs(title="Radar Chart (Normalized Means)")
    } else {
      p <- ggplot() + annotate("text", x=0, y=0, label="Radar requires >=3 vars")
    }
  } else if (plot_type == "xyz_surface") {
    if (!is.null(v1) && !is.null(v2) && !is.null(v3)) {
      df_clean <- na.omit(df[, c(v1, v2, v3)])
      if(nrow(df_clean) > 10) {
        grid_x <- seq(min(df_clean[[v1]]), max(df_clean[[v1]]), length.out=50)
        grid_y <- seq(min(df_clean[[v2]]), max(df_clean[[v2]]), length.out=50)
        grid <- expand.grid(x=grid_x, y=grid_y)
        df_safe <- df_clean
        colnames(df_safe) <- c("var1_safe", "var2_safe", "var3_safe")
        
        x_seq <- seq(min(df_safe[["var1_safe"]]), max(df_safe[["var1_safe"]]), length.out=50)
        y_seq <- seq(min(df_safe[["var2_safe"]]), max(df_safe[["var2_safe"]]), length.out=50)
        grid <- expand.grid(var1_safe=x_seq, var2_safe=y_seq)
        
        mod <- NULL
        try({
          if(xyz_fit == "linear") mod <- lm(var3_safe ~ var1_safe + var2_safe, data=df_safe)
          else if(xyz_fit == "loess") mod <- loess(var3_safe ~ var1_safe * var2_safe, data=df_safe, span=0.7)
          else if(xyz_fit == "polynomial") mod <- lm(var3_safe ~ poly(var1_safe,2) + poly(var2_safe,2), data=df_safe)
          else if(xyz_fit == "gam") {
            if(requireNamespace("mgcv", quietly=TRUE)) {
              mod <- mgcv::gam(var3_safe ~ s(var1_safe) + s(var2_safe), data=df_safe)
            } else {
              mod <- lm(var3_safe ~ var1_safe + var2_safe, data=df_safe)
            }
          } else if(xyz_fit == "tps") {
            if(requireNamespace("fields", quietly=TRUE)) {
              mod <- fields::Tps(df_safe[,c("var1_safe","var2_safe")], df_safe[["var3_safe"]])
            }
          }
        }, silent=TRUE)
        
        if(!is.null(mod)) {
          if(xyz_fit == "tps") {
            grid[["var3_safe"]] <- as.vector(predict(mod, x=as.matrix(grid[,c("var1_safe","var2_safe")])))
          } else {
            grid[["var3_safe"]] <- as.vector(predict(mod, newdata=grid))
          }
          
          colnames(grid) <- c(v1, v2, v3)
          
          p <- ggplot(grid, aes(x=.data[[v1]], y=.data[[v2]], z=.data[[v3]])) +
               geom_tile(aes(fill=.data[[v3]])) +
               geom_contour(color="white", alpha=0.5) +
               scale_fill_viridis_c() +
               labs(title=paste("XYZ Surface (", xyz_fit, ")", sep=""))
        } else {
          p <- ggplot() + annotate("text", x=0, y=0, label="Model fitting failed")
        }
      } else {
        p <- ggplot() + annotate("text", x=0, y=0, label="Not enough data for surface")
      }
    } else {
      p <- ggplot() + annotate("text", x=0, y=0, label="XYZ Surface requires 3 numeric variables.\nPlease select 3 variables in the sidebar.") + theme_void()
    }
  }
  
  return(p)
}


generate_correlation_heatmap <- function(df, vars, method = "pearson", cormat = NULL) {

  if (length(vars) < 2) return(ggplot() + annotate("text", x=0, y=0, label="Need >=2 variables"))
  
  df_clean <- na.omit(df[, vars, drop=FALSE])
  if (nrow(df_clean) < 3) return(ggplot() + annotate("text", x=0, y=0, label="Insufficient data"))
  
  if (is.null(cormat)) {
    cormat <- cor(df_clean, method = method)
  }
  
  distmat <- as.dist(1 - abs(cormat))
  hc <- hclust(distmat)
  ordered_vars <- vars[hc$order]
  
  cormat_df <- melt_cormat(cormat, "Corr")
  
  cormat_df$Var1 <- factor(cormat_df$Var1, levels = ordered_vars)
  cormat_df$Var2 <- factor(cormat_df$Var2, levels = rev(ordered_vars))
  
  p <- ggplot(cormat_df, aes(x=Var1, y=Var2, fill=Corr)) + 
    geom_tile(color = "white") +
    geom_text(aes(label = round(Corr, 2)), color = ifelse(abs(cormat_df$Corr) > 0.5, "white", "black"), size=3) +
    scale_fill_gradient2(low = "red", high = "blue", mid = "white", midpoint = 0, limits = c(-1,1), name=paste(tools::toTitleCase(method), "\nCorrelation")) +
    theme_minimal() + 
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
    labs(x="", y="", title="Hierarchical Clustering Correlation Heatmap")
  return(p)
}

generate_correlation_network <- function(df, vars, threshold = 0.3, method = "pearson", cormat = NULL) {

  if (length(vars) < 2) return(ggplot() + annotate("text", x=0, y=0, label="Need >=2 variables"))
  
  df_clean <- na.omit(df[, vars, drop=FALSE])
  if (nrow(df_clean) < 3) return(ggplot() + annotate("text", x=0, y=0, label="Insufficient data"))
  
  if (is.null(cormat)) {
    cormat <- cor(df_clean, method = method)
  }
  
  n <- length(vars)
  angles <- seq(0, 2*pi, length.out = n + 1)[1:n]
  nodes <- data.frame(
    name = vars,
    x = cos(angles),
    y = sin(angles)
  )
  
  edges <- data.frame(from=character(), to=character(), x=numeric(), y=numeric(), xend=numeric(), yend=numeric(), weight=numeric(), sign=character())
  
  for(i in 1:(n-1)) {
    for(j in (i+1):n) {
      w <- cormat[i, j]
      if (abs(w) >= threshold) {
        edges <- rbind(edges, data.frame(
          from = vars[i], to = vars[j],
          x = nodes$x[i], y = nodes$y[i],
          xend = nodes$x[j], yend = nodes$y[j],
          weight = abs(w),
          sign = ifelse(w > 0, "Positive", "Negative")
        ))
      }
    }
  }
  
  p <- ggplot() + theme_void() + labs(title = paste("Correlation Network (threshold >", threshold, ")"))
  
  if (nrow(edges) > 0) {
    p <- p + geom_segment(data = edges, aes(x=x, y=y, xend=xend, yend=yend, color=sign, linewidth=weight), alpha=0.6) +
             scale_linewidth_continuous(range = c(0.5, 3)) +
             scale_color_manual(values = c("Positive" = "blue", "Negative" = "red"))
  }
  
  p <- p + geom_point(data = nodes, aes(x=x, y=y), size=10, color="lightblue") +
           geom_text(data = nodes, aes(x=x, y=y, label=name), fontface="bold")
           
  return(p)
}

generate_partial_correlation <- function(df, vars, control_vars = NULL, method = "pearson") {

  if (length(vars) < 2) return(ggplot() + annotate("text", x=0, y=0, label="Need >=2 variables to correlate"))

  # Residualization + the rank/kendall conventions live in
  # compute_partial_correlation() so this plot and the correlation summary
  # table can never disagree about what "partial" means.
  pc <- compute_partial_correlation(df, vars, control_vars, method = method)
  if (length(pc$failed) > 0) {
    return(ggplot() + annotate("text", x=0, y=0,
      label="Could not partial out the control variables") + theme_void())
  }
  if (is.null(pc$cormat) || pc$n < 5) return(ggplot() + annotate("text", x=0, y=0, label="Insufficient data"))

  cormat <- pc$cormat
  n_ctrl <- pc$k

  cormat_df <- melt_cormat(cormat, "pCorr")
  
  cormat_df$Var1 <- factor(cormat_df$Var1, levels = vars)
  cormat_df$Var2 <- factor(cormat_df$Var2, levels = rev(vars))
  
  p <- ggplot(cormat_df, aes(x=Var1, y=Var2, fill=pCorr)) + 
    geom_tile(color = "white") +
    geom_text(aes(label = round(pCorr, 2)), color = ifelse(abs(cormat_df$pCorr) > 0.5, "white", "black"), size=3) +
    scale_fill_gradient2(low = "red", high = "blue", mid = "white", midpoint = 0, limits = c(-1,1), name="Partial\nCorrelation") +
    theme_minimal() + 
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
    labs(x="", y="",
         title = if (n_ctrl == 0) "Standard Correlation Heatmap" else paste("Partial Correlation (Controlling for", n_ctrl, "vars)"),
         subtitle = if (n_ctrl == 0) NULL else switch(method,
           spearman = "Spearman: ranks residualized on the controls (ppcor convention)",
           kendall  = "Kendall: partial tau from the inverted tau matrix (ppcor convention)",
           NULL))
  return(p)
}

generate_correlogram <- function(df, vars, method = "pearson", cormat = NULL) {

  if (length(vars) < 2) return(ggplot() + annotate("text", x=0, y=0, label="Need >=2 variables"))
  
  df_clean <- na.omit(df[, vars, drop=FALSE])
  if (nrow(df_clean) < 3) return(ggplot() + annotate("text", x=0, y=0, label="Insufficient data"))
  
  if (is.null(cormat)) {
    cormat <- cor(df_clean, method = method)
  }
  
  cormat_df <- melt_cormat(cormat, "Corr")
  
  cormat_df$Var1 <- factor(cormat_df$Var1, levels = vars)
  cormat_df$Var2 <- factor(cormat_df$Var2, levels = rev(vars))
  
  p <- ggplot(cormat_df, aes(x=Var1, y=Var2, color=Corr, size=abs(Corr))) + 
    geom_point() +
    scale_size_continuous(range = c(1, 15), guide="none") +
    scale_color_gradient2(low = "red", high = "blue", mid = "white", midpoint = 0, limits = c(-1,1)) +
    theme_minimal() + 
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
    labs(x="", y="", title="Correlogram")
  return(p)
}

# ── Spatial cross-correlogram ──────────────────────────────────────────────
# Replaces the former row-order "Lagged CCF" panel. stats::ccf() measures lag in
# ROWS of the uploaded table, which for a soil point table is upload order, not
# distance, and its +/-1.96/sqrt(n) bands additionally assume a stationary
# series - neither holds for cross-sectional spatial samples.
#
# The estimator here is the standard geostatistical one. With both variables
# standardised to zero mean and unit variance, the empirical cross variogram
# gamma_12(h) - computed by gstat with the same pair binning as every other
# variogram in the app - and the cross-covariance are related by
#     gamma_12(h) = C_12(0) - (C_12(h) + C_21(h)) / 2
# so the spatial cross-correlation at lag h is
#     rho_12(h) = r_12 - gamma_12(h)
# with r_12 the ordinary non-spatial correlation of the standardised variables
# (Goovaerts 1997 section 4.2.3; Isaaks & Srivastava 1989 ch. 4). Only the
# SYMMETRIC part of the cross-covariance is estimable from omnidirectional bins
# (pairs (i,j) and (j,i) land in the same bin), which is also why there is no
# negative-lag half: unlike a time series, an unordered point set has no
# "leads" and "lags".
#
# Coordinates are projected before binning (the app's never-measure-distance-in-
# degrees invariant). Returns list(bins, r0, n, unit, ranked, message); `message`
# is a user-facing placeholder reason and is non-NULL exactly when `bins` is NULL.
compute_spatial_cross_correlogram <- function(df, var1, var2, x_col, y_col,
                                              src_crs, proj_crs = NULL,
                                              n_bins = 15, method = "pearson") {
  out <- list(bins = NULL, r0 = NA_real_, n = 0L, unit = "m",
              ranked = !identical(method, "pearson"), message = NULL)
  fail <- function(msg) { out$message <- msg; out }

  if (is.null(x_col) || is.null(y_col) || is.null(src_crs) ||
      !all(c(x_col, y_col) %in% colnames(df))) {
    return(fail("Coordinates are not mapped yet.\nConfirm the variable mapping on the Data Setup tab."))
  }
  if (is.null(var1) || is.null(var2) || !all(c(var1, var2) %in% colnames(df))) {
    return(fail("Invalid variables specified"))
  }
  if (identical(var1, var2)) return(fail("Select two different variables"))

  d <- na.omit(df[, unique(c(var1, var2, x_col, y_col)), drop = FALSE])
  if (!is.numeric(d[[var1]]) || !is.numeric(d[[var2]])) return(fail("Both variables must be numeric"))
  if (nrow(d) < 15) return(fail("Insufficient data: at least 15 complete observations are needed"))
  # Fixed internal names: the coordinate columns are themselves selectable as
  # variables, so copying by position keeps a var1 == x_col choice from
  # producing a duplicated column name in the working frame.
  work <- data.frame(.cx = d[[x_col]], .cy = d[[y_col]],
                     .v1 = d[[var1]], .v2 = d[[var2]])

  pts <- tryCatch({
    p <- sf::st_as_sf(work, coords = c(".cx", ".cy"), crs = src_crs)
    if (!is.null(proj_crs) && !identical(proj_crs, "")) {
      p <- tryCatch(sf::st_transform(p, proj_crs), error = function(e) p)
    }
    validate_and_project_sf(p)
  }, error = function(e) NULL)
  if (is.null(pts) || nrow(pts) == 0) return(fail("Could not project the coordinates"))

  # Same coordinate deduplication (2 dp, projected) the interpolation point sets
  # use, so co-located twins do not stack the shortest bin.
  pts <- pts[!duplicated(round(sf::st_coordinates(pts), 2)), ]
  out$n <- nrow(pts)
  if (out$n < 15) return(fail("Insufficient data: at least 15 distinct locations are needed"))

  crs_unit <- tryCatch(sf::st_crs(pts)$units, error = function(e) NULL)
  if (!is.null(crs_unit) && nzchar(crs_unit)) out$unit <- crs_unit

  # Rank transform for the rank-based methods: Spearman is the product-moment
  # correlation of ranks, so the whole estimator simply runs on ranks. Kendall
  # has no distance-binned analogue and is served by the same rank-based curve
  # (named as such in the plot subtitle).
  v1v <- pts$.v1; v2v <- pts$.v2
  if (out$ranked) { v1v <- rank(v1v); v2v <- rank(v2v) }
  s1 <- stats::sd(v1v); s2 <- stats::sd(v2v)
  if (!is.finite(s1) || !is.finite(s2) || s1 == 0 || s2 == 0) {
    return(fail("A selected variable is constant - no correlation is defined"))
  }
  pts$z1 <- (v1v - mean(v1v)) / s1
  pts$z2 <- (v2v - mean(v2v)) / s2
  out$r0 <- stats::cor(pts$z1, pts$z2)

  lags <- calc_scientific_lags(pts)
  # A cleared numericInput arrives as NA, not as NULL.
  nb <- suppressWarnings(as.integer(n_bins)[1])
  if (is.na(nb)) nb <- 15L
  width <- lags$cutoff / max(3L, min(50L, nb))
  if (!is.finite(width) || width <= 0) return(fail("Could not derive distance bins from the coordinates"))

  vg <- tryCatch({
    g <- gstat::gstat(NULL, id = "z1", formula = z1 ~ 1, data = pts)
    g <- gstat::gstat(g, id = "z2", formula = z2 ~ 1, data = pts)
    gstat::variogram(g, cross = TRUE, cutoff = lags$cutoff, width = width)
  }, error = function(e) NULL)
  if (is.null(vg)) return(fail("The cross variogram could not be computed for this pair"))

  cross <- vg[as.character(vg$id) == "z1.z2", , drop = FALSE]
  if (nrow(cross) == 0) return(fail("No point pairs fall inside the lag distance range"))

  out$bins <- data.frame(
    dist  = as.numeric(cross$dist),
    np    = as.integer(cross$np),
    gamma = as.numeric(cross$gamma),
    rho   = out$r0 - as.numeric(cross$gamma),
    stringsAsFactors = FALSE
  )
  out
}

generate_spatial_cross_correlogram <- function(df, var1, var2, x_col, y_col,
                                               src_crs, proj_crs = NULL,
                                               n_bins = 15, method = "pearson") {
  res <- compute_spatial_cross_correlogram(df, var1, var2, x_col, y_col,
                                           src_crs, proj_crs, n_bins, method)
  if (is.null(res$bins)) {
    return(ggplot() + annotate("text", x = 0, y = 0, label = res$message, size = 4.5) + theme_void())
  }

  b <- res$bins
  # Journel & Huijbregts' rule of thumb for variogram bins: below ~30 pairs the
  # estimate is too noisy to read, so those bins are greyed instead of dropped.
  b$reliable <- b$np >= 30

  p <- ggplot(b, aes(x = dist, y = rho)) +
    geom_hline(yintercept = 0, color = "gray50") +
    geom_hline(yintercept = res$r0, linetype = "dashed", color = "#2c7fb8") +
    geom_line(color = "gray40", linewidth = 0.6) +
    geom_point(aes(size = np, color = reliable)) +
    scale_color_manual(values = c("TRUE" = "#2c7fb8", "FALSE" = "grey65"), guide = "none") +
    scale_size_continuous(range = c(1.5, 6), name = "Pairs") +
    theme_minimal() +
    labs(
      title = sprintf("Spatial Cross-Correlogram: %s vs %s", var1, var2),
      subtitle = sprintf("%srho(h) = r - gamma12(h) on standardised values | non-spatial r = %.3f | n = %d",
                         if (res$ranked) "Rank-based (Spearman-type). " else "",
                         res$r0, res$n),
      x = sprintf("Lag distance (%s)", res$unit),
      y = "Cross-correlation",
      caption = "Dashed line = non-spatial correlation. Point size = pairs per bin; grey = fewer than 30 pairs."
    )
  return(p)
}

check_collinearity <- function(df, vars, threshold = 0.95) {
  res <- detect_multicollinearity_engine(df, vars = vars, pairwise_threshold = threshold, vif_threshold = 10)
  
  has_coll <- res$has_collinearity || (length(res$dropped) > 0)
  
  pairs_df <- res$pairs
  if (length(res$dropped) > 0) {
    if (is.null(pairs_df)) {
      pairs_df <- data.frame(var1 = character(), var2 = character(), r = numeric(), stringsAsFactors = FALSE)
    }
    # The engine drops ZERO-VARIANCE covariates into the same vector as the
    # collinear ones; reporting a constant to the PCA user as a collinearity
    # problem sends them to inspect a correlation that does not exist.
    for (d_var in res$dropped) {
      pairs_df <- rbind(pairs_df, data.frame(
        var1 = d_var,
        var2 = if (d_var %in% res$dropped_constant) "Constant (no variance)" else "High VIF (> 10)",
        r = NA,
        stringsAsFactors = FALSE
      ))
    }
  }
  
  return(list(has_collinearity = has_coll, pairs = pairs_df))
}

generate_pca_scree <- function(pca_res) {

  var_explained <- pca_res$sdev^2 / sum(pca_res$sdev^2)
  df_scree <- data.frame(PC = 1:length(var_explained), Variance = var_explained)
  
  p <- ggplot(df_scree, aes(x = PC, y = Variance)) +
    geom_bar(stat = "identity", fill = "steelblue", alpha=0.7) +
    geom_line(color = "red", linewidth=1) +
    geom_point(color = "red", size=2) +
    scale_x_continuous(breaks = 1:nrow(df_scree)) +
    theme_minimal() +
    labs(title = "Scree Plot (Variance Explained by PC)", y = "Proportion of Variance", x = "Principal Component")
  return(p)
}

generate_pca_biplot <- function(pca_res, original_df, pc_x = 1, pc_y = 2, group_col = NULL) {

  scores <- as.data.frame(pca_res$x)
  
  if (!is.null(group_col) && group_col %in% colnames(original_df)) {
    scores$Group <- original_df[[group_col]]
  } else {
    scores$Group <- "All"
  }
  
  loadings <- as.data.frame(pca_res$rotation)
  var_exp <- round(pca_res$sdev^2 / sum(pca_res$sdev^2) * 100, 1)
  
  mult <- min(
    (max(scores[, pc_x]) - min(scores[, pc_x])) / (max(loadings[, pc_x]) - min(loadings[, pc_x])),
    (max(scores[, pc_y]) - min(scores[, pc_y])) / (max(loadings[, pc_y]) - min(loadings[, pc_y]))
  ) * 0.7
  
  loadings_scaled <- loadings * mult
  
  p <- ggplot() +
    geom_point(data = scores, aes(x = .data[[paste0("PC", pc_x)]], y = .data[[paste0("PC", pc_y)]], color = .data[["Group"]]), alpha = 0.6) +
    geom_segment(data = loadings_scaled, aes(x = 0, y = 0, xend = .data[[paste0("PC", pc_x)]], yend = .data[[paste0("PC", pc_y)]]), arrow = arrow(length = unit(0.2, "cm")), color = "red", alpha=0.8) +
    geom_text(data = loadings_scaled, aes(x = .data[[paste0("PC", pc_x)]], y = .data[[paste0("PC", pc_y)]], label = rownames(loadings_scaled)), color = "darkred", vjust = "outward", hjust = "outward", size=4) +
    theme_minimal() +
    labs(title = paste("Biplot (PC", pc_x, " vs PC", pc_y, ")", sep=""),
         x = paste("PC", pc_x, " (", var_exp[pc_x], "%)", sep=""),
         y = paste("PC", pc_y, " (", var_exp[pc_y], "%)", sep=""))
  
  return(p)
}

generate_pca_bar_plot <- function(values_named, val_name, title_text, y_label, fill_color = NULL, exp_cont = NULL) {
  df <- data.frame(Variable = names(values_named), Value = values_named)
  
  if (val_name == "Loading") {
    df <- df[order(abs(df$Value), decreasing = TRUE), ]
  } else {
    df <- df[order(df$Value, decreasing = TRUE), ]
  }
  df$Variable <- factor(df$Variable, levels = rev(df$Variable))
  
  p <- ggplot(df, aes(x = Variable, y = Value))
  if (val_name == "Loading") {
    p <- p + geom_bar(stat = "identity", aes(fill = Value > 0)) +
      scale_fill_manual(values = c("TRUE" = "steelblue", "FALSE" = "indianred"), guide = "none")
  } else {
    p <- p + geom_bar(stat = "identity", fill = fill_color, alpha = 0.8)
  }
  
  if (!is.null(exp_cont)) {
    p <- p + geom_hline(yintercept = exp_cont, linetype = "dashed", color = "red")
  }
  
  p <- p + coord_flip() + theme_minimal() + labs(title = title_text, x = "Variable", y = y_label)
  if (!is.null(exp_cont)) p <- p + labs(caption = "Dashed line indicates expected average contribution")
  
  return(p)
}

generate_pca_loadings <- function(pca_res, pc = 1) {
  generate_pca_bar_plot(pca_res$rotation[, pc], "Loading", paste("Loadings for PC", pc), "Loading Weight")
}

generate_pca_contribution <- function(pca_res, pc = 1) {
  loadings <- pca_res$rotation[, pc]
  contrib <- (loadings^2) * 100
  generate_pca_bar_plot(contrib, "Contribution", paste("Variable Contribution to PC", pc), "Contribution (%)", "coral", 100 / length(contrib))
}

generate_pca_cos2 <- function(pca_res, axes = 1:2) {
  coord <- sweep(pca_res$rotation[, axes, drop=FALSE], 2, pca_res$sdev[axes], "*")
  cos2 <- rowSums(coord^2)
  generate_pca_bar_plot(cos2, "Cos2", paste("Quality of Representation (cos2) on PC", paste(axes, collapse=" & ")), "cos2", "mediumseagreen")
}

generate_pca_cumvar <- function(pca_res) {

  var_explained <- pca_res$sdev^2 / sum(pca_res$sdev^2)
  cum_var <- cumsum(var_explained)
  
  df_cum <- data.frame(PC = 1:length(cum_var), CumVar = cum_var)
  
  p <- ggplot(df_cum, aes(x = PC, y = CumVar)) +
    geom_line(color = "darkblue", linewidth=1.2) +
    geom_point(color = "orange", size=3) +
    geom_hline(yintercept = 0.8, linetype="dashed", color="red", alpha=0.6) +
    scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
    scale_x_continuous(breaks = 1:nrow(df_cum)) +
    theme_minimal() +
    labs(title = "Cumulative Variance Explained", 
         x = "Principal Component", y = "Cumulative Variance",
         caption = "Dashed line indicates 80% threshold")
  return(p)
}

generate_pca_mahalanobis <- function(pca_res) {

  # PC scores are uncorrelated by construction, so their covariance is
  # diag(sdev^2); near-zero-variance PCs (collinear inputs) would make that
  # matrix numerically singular, so they are excluded from the distance
  #
  # This is the CLASSICAL Mahalanobis distance: the centre and scatter are the
  # ordinary mean/covariance, which the outliers themselves contribute to. A
  # small cluster of extreme observations therefore inflates the covariance and
  # can pull its own distance back under the threshold (masking). A robust
  # estimator (MCD, robustbase::covMcd on the retained scores) is the standard
  # remedy but is a new dependency; the panel names its estimator instead so the
  # limitation is visible where it matters. See scientific_guide.md 8.2.
  keep <- pca_res$sdev > max(pca_res$sdev) * 1e-8
  scores <- as.data.frame(pca_res$x[, keep, drop = FALSE])
  center <- colMeans(scores)
  cov_mat <- diag(pca_res$sdev[keep]^2, nrow = sum(keep))

  md <- mahalanobis(scores, center, cov_mat)
  df_md <- data.frame(Index = 1:length(md), Distance = md)

  thresh <- qchisq(0.975, df = ncol(scores))
  
  p <- ggplot(df_md, aes(x = Index, y = Distance)) +
    geom_point(aes(color = Distance > thresh), size=2, alpha=0.8) +
    geom_segment(aes(x=Index, xend=Index, y=0, yend=Distance, color=Distance > thresh)) +
    geom_hline(yintercept = thresh, linetype="dashed", color="red") +
    scale_color_manual(values = c("TRUE" = "red", "FALSE" = "black"), guide="none") +
    theme_minimal() +
    labs(title = "Mahalanobis Distance (Classical Estimator)",
         subtitle = "Classical mean/covariance: outliers inflate the covariance and can mask themselves",
         x = "Observation Index", y = "Distance",
         caption = sprintf("Dashed line indicates the 97.5%% Chi-Square threshold (df = %d retained PCs)", ncol(scores)))
  return(p)
}

generate_pca_biplot_3d <- function(pca_res, df, pc_x=1, pc_y=2, pc_z=3, group_col=NULL) {

  
  scores <- as.data.frame(pca_res$x)
  if (!is.null(group_col) && group_col %in% colnames(df)) {
    scores$Group <- df[[group_col]]
  } else {
    scores$Group <- factor("All")
  }
  
  var_exp <- round(pca_res$sdev^2 / sum(pca_res$sdev^2) * 100, 1)
  
  p <- plot_ly(scores, x = ~get(paste0("PC", pc_x)), y = ~get(paste0("PC", pc_y)), z = ~get(paste0("PC", pc_z)), 
               color = ~Group, type = "scatter3d", mode = "markers",
               marker = list(size = 4, opacity = 0.8)) %>%
       layout(title = "3D PCA Biplot",
              scene = list(
                xaxis = list(title = paste0("PC", pc_x, " (", var_exp[pc_x], "%)")),
                yaxis = list(title = paste0("PC", pc_y, " (", var_exp[pc_y], "%)")),
                zaxis = list(title = paste0("PC", pc_z, " (", var_exp[pc_z], "%)"))
              ))
  return(p)
}

add_styled_points <- function(map, pts_sf, color_by = "none", custom_colors = NULL,
                              show_labels = FALSE, label_field = "none",
                              label_size = 11, marker_size = 3,
                              popup_fn = NULL, legend_layer_id = NULL) {

  crs_obj <- sf::st_crs(pts_sf)
  pts_view <- if (is.na(crs_obj$epsg) || crs_obj$epsg != 4326) sf::st_transform(pts_sf, 4326) else pts_sf
  if (nrow(pts_view) == 0) return(map)

  use_groups <- color_by != "none" && color_by %in% colnames(pts_view)

  if (use_groups && !is.null(custom_colors)) {
    grp_vals <- as.character(pts_view[[color_by]])
    groups <- sort(unique(grp_vals))
    missing <- setdiff(groups, names(custom_colors))
    if (length(missing) > 0) {
      extra <- generate_group_palette(missing, "Set1")
      custom_colors <- c(custom_colors, extra)
    }
    pal_fn <- leaflet::colorFactor(
      palette = unname(custom_colors[groups]),
      domain = groups
    )
    fill_colors <- pal_fn(grp_vals)
    border_color <- "white"
    fill_opacity <- 0.85

    map <- map %>% leaflet::addLegend(
      position = "bottomleft",
      colors = unname(custom_colors[groups]),
      labels = groups,
      title = color_by,
      opacity = 0.9,
      layerId = legend_layer_id
    )
  } else {
    fill_colors <- "cyan"
    border_color <- "cyan"
    fill_opacity <- 0.5
  }

  popups <- NULL
  if (!is.null(popup_fn)) {
    df_clean <- sf::st_drop_geometry(pts_view)
    popups <- vapply(seq_len(nrow(df_clean)), function(i) popup_fn(df_clean[i, ]), character(1))
  }

  map <- map %>% leaflet::addCircleMarkers(
    data = pts_view,
    radius = marker_size,
    color = border_color,
    weight = 1,
    fillColor = fill_colors,
    fillOpacity = fill_opacity,
    opacity = 1,
    popup = popups,
    group = "styled_points"
  )

  if (show_labels && label_field != "none" && label_field %in% colnames(pts_view)) {
    raw_vals <- pts_view[[label_field]]
    label_vals <- if (is.numeric(raw_vals)) {
      ifelse(is.na(raw_vals), NA_character_, sprintf("%.2f", raw_vals))
    } else {
      as.character(raw_vals)
    }
    map <- map %>% leaflet::addLabelOnlyMarkers(
      data = pts_view,
      label = label_vals,
      labelOptions = leaflet::labelOptions(
        noHide = TRUE, direction = "top", textOnly = TRUE,
        offset = c(0, -8),
        style = list(
          "font-size" = paste0(label_size, "px"),
          "font-weight" = "bold",
          "color" = "white",
          "text-shadow" = "1px 1px 2px rgba(0,0,0,0.9), -1px -1px 2px rgba(0,0,0,0.9), 1px -1px 2px rgba(0,0,0,0.9), -1px 1px 2px rgba(0,0,0,0.9)"
        )
      ),
      group = "styled_labels"
    )
  }

  map
}
